# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - 'aducm3029.cmake'
    - 'CMakeLists.txt'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install cross-compiler
      run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

    - name: download packs
      run: |
        wget https://github.com/ARM-software/CMSIS_5/releases/download/5.4.0/ARM.CMSIS.5.4.0.pack
        wget http://download.analog.com/tools/EZBoards/CM302x/Releases/AnalogDevices.ADuCM302x_DFP.3.2.0.pack
        wget http://download.analog.com/tools/EZBoards/ADICUP3029/Releases/AnalogDevices.EVAL-ADICUP3029_BSP.1.1.0.pack

    - name: extract packs
      run: |
        unzip ARM.CMSIS.5.4.0.pack -d ARM.CMSIS.5.4.0
        unzip AnalogDevices.ADuCM302x_DFP.3.2.0.pack -d AnalogDevices.ADuCM302x_DFP.3.2.0
        unzip AnalogDevices.EVAL-ADICUP3029_BSP.1.1.0.pack -d AnalogDevices.EVAL-ADICUP3029_BSP.1.1.0

    - name: build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../aducm3029.cmake ..
        make
